config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  resources :users do
    get :favorites, on: :collection
    member do
      get 'logout'
    end
  end
  
  resources :items do
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'item_list'
      get 'brand_index'
    end
    resources :reviews
  
  end
  resources :favorites, only: :index
  resources :reviews


end

app/models/age.rb
class Age < ActiveHash::Base
  include ActiveHash::Associations
  has_many :users

  self.data = [
    {id: 0, age: '--'}, {id: 1, age: '10代'}, {id: 2, age: '20代'}, {id: 3, age: '30代'},
    {id: 4, age: '40代'}, {id: 5, age: '50代'}, {id: 6, age: '60代'},
    {id: 7, age: '70代以上'}
  ]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates_uniqueness_of :item_id, scope: :user_id
end

app/models/gender.rb
class Gender < ActiveHash::Base
  include ActiveHash::Associations
  has_many :users
  
  self.data = [
    {id: 0, gender: '--'}, {id: 1, gender: '女性'},
    {id: 2, gender: '男性'}, {id: 3, gender: 'その他'}
  ]
  
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :reviews
  has_many :users, through: :reviews
  has_many :favorites, dependent: :destroy
  belongs_to :user, optional: true
  belongs_to_active_hash :maker

  mount_uploader :image_url, ItemImageUploader
end

app/models/maker.rb
class Maker < ActiveHash::Base
  include ActiveHash::Associations
  has_many :items
  
  self.data = [
    {id: 0, maker: 'アマタケ'}, {id: 1, maker: 'セブンイレブン'},
    {id: 2, maker: 'ファミリーマート'}, {id: 3, maker: 'ローソン'}
  ]
  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :user_id, presence: true, uniqueness: true

  mount_uploader :commentImg, CommentImgUploader
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :age
  belongs_to_active_hash :gender
  has_many :item, through: :reviews 
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy


  # validates :comment, presence: true, length: { maximum: 200 }
  

        
  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: 'ゲスト', nickname: 'ゲストユーザー' ) do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  mount_uploader :avaterImg, AvaterImgUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname ])
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_item
  before_action :authenticate_user!

  def index
  end
  
  def create
    @favorite = Favorite.create(user_id: current_user.id, item_id: @item.id)
  end

  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, item_id: @item.id)
    @favorite.destroy
  end

  private
  def set_item
    @item = Item.find(params[:item_id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :show, :update]
  
  def index
    @item = Item.find(1)
  end

  def show
    if user_signed_in? 
      @user = User.find(current_user.id)
    end
    @review = Review.new
    @reviews = @item.reviews.includes(:user)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
    if @item.save
      redirect_to new_item_path, notice: 'アイテムの新規登録に成功しました。'
    else
      render new_item_path, notice: 'アイテム登録に失敗しました。'
    end
  end

  def edit
    @itemImg = @item.image_url.to_s
  end

  def update
    @item.update(item_params)
    redirect_to item_path(@item.id), notice: '商品情報が更新されました。'
  end

  private

  def item_params
    params.require(:item).permit(:name, :maker_id, :maker_url, :price, :image_url)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  def index
  end

  def create
    review = Review.create(review_params)
    redirect_to "/items/#{review.item.id}"
  end

  def show
  end

  def edit
    @item = Item.find(params[:item_id])
  end

  def destroy
    @review.destroy
    redirect_to "/items/#{@review.item_id}"
  end

  def update
    @review.update(review_params)
    redirect_to "/items/#{@review.item_id}"
  end

  private

  def review_params
    params.require(:review).permit(:title, :evaluation, :comment, :commentImg).merge(user_id: current_user.id, item_id: params[:item_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: :destroy

  def edit
    @user = User.find(current_user.id)
    if @user.avaterImg?
      @userAvater = @user.avaterImg.to_s
    else
      @userAvater = nil
    end
  end

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end

  
  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
  
  def after_update_path_for(resource)
    user_path(@user.id)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_userImg, only: [:show, :edit]

  def new
  end

  def show
    @userFav = User.find(params[:id])
    @items = @userFav.items

    favorites = Favorite.where(user_id: current_user.id).pluck(:item_id)
    @favorite_list = Post.find(favorites)
  end

  def edit
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(current_user.id), notice: 'ユーザー情報が更新されました。'
  end

  private
  
  def user_params
    params.require(:user).permit(:avaterImg, :name, :nickname, :age_id, :gender_id, :introduction)
  end

  def set_userImg
    @user = User.find(current_user.id)
    if @user.avaterImg?
      @userAvater = @user.avaterImg.to_s
    else
      @userAvater = nil
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<div class="item-list">
  <div class="container">
    <h2 class="item-list__title">お気に入りランキング</h2>
      <div class="item-list__index uk-child-width-expand@s uk-text-center uk-grid">
        <%= link_to "#" do%>
          <div class="item-box uk-card uk-card-default uk-card-body uk-width-auto@m">
            <%= image_tag("ピザ.jpg") %>
            <%# <img src="ピザ.jpg" alt=""> %>
            <p class="item-name">サラダチキンA</p>
            <hr>
            <p class="maker">アマタケ</p>
            <hr>
            <p class="reviews">口コミ評価</p>
            <p class="reviews">★★★★☆</p>
            <hr>
            <p>ランキング1位</p>
          </div>
        <% end %>
        <%= link_to "#" do%>
          <div class="item-box uk-card uk-card-default uk-card-body uk-width-auto@m">
            <%= image_tag("ピザ.jpg") %>
            <%# <img src="ピザ.jpg" alt=""> %>
            <p class="item-name">サラダチキンA</p>
            <hr>
            <p class="maker">アマタケ</p>
            <hr>
            <p class="reviews">口コミ評価</p>
            <p class="reviews">★★★★☆</p>
            <hr>
            <p>ランキング1位</p>
          </div>
        <% end %>
        <%= link_to "#" do%>
          <div class="item-box uk-card uk-card-default uk-card-body uk-width-auto@m">
            <%= image_tag("ピザ.jpg") %>
            <%# <img src="ピザ.jpg" alt=""> %>
            <p class="item-name">サラダチキンA</p>
            <hr>
            <p class="maker">アマタケ</p>
            <hr>
            <p class="reviews">口コミ評価</p>
            <p class="reviews">★★★★☆</p>
            <hr>
            <p>ランキング1位</p>
          </div>
        <% end %>
        <%= link_to "#" do%>
        <div class="item-box uk-card uk-card-default uk-card-body uk-width-auto@m">
            <%= image_tag("ピザ.jpg") %>
            <%# <img src="ピザ.jpg" alt=""> %>
            <p class="item-name">サラダチキンA</p>
            <hr>
            <p class="maker">アマタケ</p>
            <hr>
            <p class="reviews">口コミ評価</p>
            <p class="reviews">★★★★☆</p>
            <hr>
            <p>ランキング1位</p>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/items/brand_index.html.erb
<div class="item-list">
  <div class="container">
    <h2 class="item-list__title">ブランド一覧</h2>
      <div class="item-list__index uk-child-width-expand@s uk-text-center uk-grid">
        <%= link_to "#" do%>
          <div class="item-box uk-card uk-card-default uk-card-body uk-width-auto@m">
            <%= image_tag("ピザ.jpg") %>
            <%# <img src="ピザ.jpg" alt=""> %>
            <p class="maker">アマタケ</p>
          </div>
        <% end %>
        <%= link_to "#" do%>
          <div class="item-box uk-card uk-card-default uk-card-body uk-width-auto@m">
            <%= image_tag("ピザ.jpg") %>
            <%# <img src="ピザ.jpg" alt=""> %>
            <p class="maker">セブンイレブン</p>
          </div>
        <% end %>
        <%= link_to "#" do%>
          <div class="item-box uk-card uk-card-default uk-card-body uk-width-auto@m">
            <%= image_tag("ピザ.jpg") %>
            <%# <img src="ピザ.jpg" alt=""> %>
            <p class="maker">ファミリーマート</p>
          </div>
        <% end %>
        <%= link_to "#" do%>
        <div class="item-box uk-card uk-card-default uk-card-body uk-width-auto@m">
            <%= image_tag("ピザ.jpg") %>
            <%# <img src="ピザ.jpg" alt=""> %>
            <p class="maker">ローソン</p>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/items/edit.html.erb
<% if current_user.admin? %>
<div class="newItem">
  <div class="container">
    <h2 class="newItem__title">アイテム情報の編集</h2>
    <div class="newItem__contents">
      <%= form_with(model: @item, local: true, id: 'new_item') do |f| %>
        <div class="field">
          <%= f.label :name, "商品名", class: "newItem__content" %>
          <%= f.text_field :name, placeholder: "サラダチキン", autofocus: true %>
        </div>
        <div class="field">
          <%= f.label :maker_id, "メーカー名", class: "newItem__content" %>
          <%= f.collection_select :maker_id, Maker.all, :id, :maker %>
        </div>
        <div class="field">
          <%= f.label :maker_url, "メーカーURL", class: "newItem__content" %>
          <%= f.text_field :maker_url, placeholder: "※http:// sample.com" %>
        </div>
        <div class="field">
          <%= f.label :price, "価格", class: "newItem__content" %>
          <%= f.text_field :price %>
        </div>
        <div class="field">
          <p class="newItem__content">保存中の商品画像</p>
          <%= image_tag @itemImg %>
        </div>
        <div class="field">
          <%= f.label :image_url, "商品画像", class: "newItem__content" %>
          <%= f.file_field :image_url %>
        </div>
        <div class="actions">
          <%= f.submit "編集内容を保存する" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/items/index.html.erb
<div class="about">
  <h1 class="about__top">え？飽きちゃったの？</h1>
  <%= link_to "My Salad Chikenを利用する", "#"%>
</div>

<div class="introduce">
  <div class="container">
    <div class="introduction">
      <h2 class="introduction-title">My Salad Chickenとは</h2>
    </div>
    <p>手軽に高タンパク質なものを摂取したい時に食べるサラダチキン<br>
      しかし、同じ様な味では飽きてしまう...という方に向けた、<br>
      サラダチキンに特化した口コミサイトです。</p>
    <div class="introduction__contents uk-child-width-expand@s uk-text-center uk-grid">
      <div class="introduction-box uk-card uk-card-default uk-card-body">
        <span class="fas fa-check-square"></span>
        <h3 class="introduction-title">リアルな口コミ</h3>
        <p class="introduction-text">購入者によるリアルな<br>口コミで失敗しない</p>
      </div>
      <div class="introduction-box uk-card uk-card-default uk-card-body">
        <span class="fas fa-search"></span>
        <h3 class="introduction-title">検索性</h3>
        <p class="introduction-text">お気に入りやランキング、<br>最新の口コミから検索可能</p>
      </div>
      <div class="introduction-box uk-card uk-card-default uk-card-body">
        <span class="fas fa-reply"></span>
        <h3 class="introduction-title">レスポンシブ</h3>
        <p class="introduction-text">PCやスマートフォン<br>どちらからでも見やすい設計</p>
      </div>
    </div>
  </div>
</div>

<div class="item-list">
  <div class="container">
    <h2 class="item-list__title">お気に入りランキング</h2>
      <div class="item-list__index uk-child-width-expand@s uk-text-center uk-grid">
        <%= link_to item_path(@item) do%>
          <div class="item-box uk-card uk-card-default uk-card-body uk-width-auto@m">
              <%= image_tag("ピザ.jpg") %>
              <p class="item-name">サラダチキンA</p>
              <hr>
              <p class="maker">アマタケ</p>
              <hr>
              <p class="reviews">口コミ評価</p>
              <p class="reviews">★★★★☆</p>
              <hr>
              <p>ランキング1位</p>
          </div>
        <% end %>
        <%= link_to "#" do%>
          <div class="item-box uk-card uk-card-default uk-card-body uk-width-auto@m">
              <%= image_tag("ピザ.jpg") %>
              <p class="item-name">サラダチキンA</p>
              <p class="maker">アマタケ</p>
          </div>
        <% end %>
        <%= link_to "#" do%>
          <div class="item-box uk-card uk-card-default uk-card-body uk-width-auto@m">
              <%= image_tag("ピザ.jpg") %>
              <p class="item-name">サラダチキンA</p>
              <p class="maker">アマタケ</p>
          </div>
        <% end %>
        <%= link_to "#" do%>
          <div class="item-box uk-card uk-card-default uk-card-body uk-width-auto@m">
              <%= image_tag("ピザ.jpg") %>
              <p class="item-name">サラダチキンA</p>
              <p class="maker">アマタケ</p>
          </div>
        <% end %>
      </div>
      <%= link_to "お気に入りランキング一覧へ", favorites_path, class: "item-index" %>

    <h2 class="review">新着の口コミ一覧</h2>
      <div class="review__index uk-child-width-expand@s uk-text-center uk-grid">
        <div class="review__box uk-card uk-card-default uk-card-body">
          <div class="review__left">
            <%= link_to "#" do %>
              <div class="user　uk-card uk-width-auto@m">
                <p>ユーザー</p>
                <%= image_tag("ピザ.jpg") %>
                <p class="user__name">test</p>
              </div>
            <% end %>
          </div>  
            <div class="review__center user__comment uk-card uk-width-expand@m">
              <ul class="review__contents">
                <li class="review__timestamp">2020/09/09/10:00</li>
                <li class="review__title">評価：３　title：投稿タイトル</li>
                <li class="review__star">★★★★☆</li>
                <li>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</li>
              </ul>
            </div>
          <div class="review__right">
            <%= link_to "#" do%>
              <div class="review__item">
                <ul>
                  <li><%= image_tag("ピザ.jpg") %></li>
                  <li class="item-name">サラダチキンA</li>
                  <li class="maker">アマタケ</li>
                </ul>
              </div>
          <% end %>
          </div>  
        </div>
      </div>
      <div class="review__index uk-child-width-expand@s uk-text-center uk-grid">
        <div class="review__box uk-card uk-card-default uk-card-body">
          <div class="review__left">
            <%= link_to "#" do %>
              <div class="user　uk-card uk-width-auto@m">
                <p>ユーザー</p>
                <%= image_tag("ピザ.jpg") %>
                <p class="user__name">test</p>
              </div>
            <% end %>
          </div>  
            <div class="review__center user__comment uk-card uk-width-expand@m">
              <ul class="review__contents">
                <li class="review__timestamp">2020/09/09/10:00</li>
                <li class="review__title">評価：３　title：投稿タイトル</li>
                <li class="review__star">★★★★☆</li>
                <li>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</li>
              </ul>
            </div>
          <div class="review__right">
            <%= link_to "#" do%>
              <div class="review__item">
                <ul>
                  <li><%= image_tag("ピザ.jpg") %></li>
                  <li class="item-name">サラダチキンA</li>
                  <li class="maker">アマタケ</li>
                </ul>
              </div>
            <% end %>
          </div>  
        </div>
      </div>
      <div class="review__index uk-child-width-expand@s uk-text-center uk-grid">
        <div class="review__box uk-card uk-card-default uk-card-body">
          <div class="review__left">
            <%= link_to "#" do %>
              <div class="user　uk-card uk-width-auto@m">
                <p>ユーザー</p>
                <%= image_tag("ピザ.jpg") %>
                <p class="user__name">test</p>
              </div>
            <% end %>
          </div>  
            <div class="review__center user__comment uk-card uk-width-expand@m">
              <ul class="review__contents">
                <li class="review__timestamp">2020/09/09/10:00</li>
                <li class="review__title">評価：３　title：投稿タイトル</li>
                <li class="review__star">★★★★☆</li>
                <li>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</li>
              </ul>
            </div>
          <div class="review__right">
            <%= link_to "#" do%>
              <div class="review__item">
                <ul>
                  <li><%= image_tag("ピザ.jpg") %></li>
                  <li class="item-name">サラダチキンA</li>
                  <li class="maker">アマタケ</li>
                </ul>
              </div>
          <% end %>
          </div>  
        </div>
      </div>
      <%= link_to "新着の口コミ一覧へ", reviews_path, class: "item-index" %>
  </div>
</div>

app/views/items/show.html.erb
<div class="itemShow">
  <div class="container">
    <h2>サラダチキン詳細情報</h2>
    <div class="itemShow__contents">
      <div class="itemShow__left">
        <%= image_tag @item.image_url.to_s %>
      </div>
      <div class="itemShow__right">
        <ul class="itemShow__profiles">
          <li class="itemShow__details itemShow__name">　商品名：　　<%= @item.name %>　</li>
          <li class="itemShow__details itemShow__unitPrice">　　単価：　　<%= @item.price %>円(税抜)</li>
          <li class="itemShow__details itemShow__maker">メーカー：　　<%= link_to @item.maker.maker, @item.maker_url, target: "_blank", rel: 'noopener' %></li>
          <% if user_signed_in? %>
            <% if !Favorite.exists?(user_id: current_user.id, item_id: @item.id) %>
              <%= link_to "お気に入り登録", item_favorites_path(@item), method: :post, class: "btn"%>
            <% else %>
              <%= link_to "お気に入り登録中", item_favorites_path(@item), method: :delete, class: "btn" %>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
    <% if current_user.admin? %>
        <%= link_to "商品情報の編集", edit_item_path(@item.id), class: "btn" %>
    <% end %>
  </div>
</div>

<div class="item-list">
  <div class="container">
    <% if @reviews.present? %>
    <h2 class="title">〜口コミ一覧〜</h2>
      <% @reviews.each do |review| %>
        <div class="review__index uk-child-width-expand@s uk-text-center uk-grid">
          <div class="review__box uk-card uk-card-default uk-card-body">
            <div class="review__left">
              <%= link_to user_path(review.user_id) do %>
                <div class="user uk-card uk-width-auto@m">
                  <p><%= review.user.nickname %></p>
                  <% if review.user.avaterImg.url %>
                    <%= image_tag review.user.avaterImg.url %>
                  <% else %>
                    <%= image_tag "userIcon.png" %>
                  <% end %>
                  <div class="profile">
                    <ul class="age">
                      <li>年齢層</li>
                      <li><%= review.user.age.age %></li>
                    </ul>
                    <ul class="gender">
                      <li>性別</li>
                      <li><%= review.user.gender.gender %></li>
                    </ul>
                  </div>
                </div>
              <% end %>
            </div>  
              <div class="review__center user__comment uk-card uk-width-expand@m">
                <ul class="review__contents arrow_box">
                  <li class="review__timestamp"><%= review.updated_at.strftime('%Y/%m/%d/ %H:%M') %></li>
                  <li class="review__evaluation">評価：<%= review.evaluation %><span>｜</span>★★★☆☆</li>
                  <li class="review__title">投稿タイトル | <%= review.title %></li>
                  <li><%= review.comment %></li>
                  <li class="review__image"><%= image_tag review.commentImg.url if review.commentImg.url.present? %></li>
                </ul>

              </div>
            <div class="review__right">
              <%= link_to "#" do%>
                <div class="review__item">
                  <ul class="review__link">
                    <li><%= image_tag("ピザ.jpg") %></li>
                    <li class="item-name">サラダチキンA</li>
                    <li class="maker">アマタケ</li>
                  </ul>
                </div>
              <% end %>
              <% if user_signed_in? && current_user.id == review.user.id %>
                <div class="review__edit">
                  <%= link_to "投稿を編集", edit_item_review_path(review.item_id, review.id), class: " btn" %>
                  <%= link_to "投稿を削除", review_path(review.id), class: "btn", method: :delete, data: { confirm: "【確認】投稿した口コミを削除してもよろしいでしょうか？" } %>
                </div>
              <% end %>
            </div>  
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="reviewForm">
    <div class="container">
      <% if current_user %>
        <h2 class="reviewForm__title">口コミを投稿する</h2>
        <%= form_with(model: [@item, @review], local: true) do |f| %>
          <div class="field">
            <%= f.label :title, "投稿タイトル", class: "reviewForm__content" %>
            <%= f.text_field :title %>
          </div>
          <div class="field">
            <%= f.label :evaluation, "評価", class: "reviewForm__content" %>
            <%= f.text_field :evaluation %>
          </div>
          <div class="field">
            <%= f.label :comment, "口コミ内容", class: "reviewForm__content " %>
            <%= f.text_area :comment, placeholder: "※200文字まで",maxlength: 200 %>
          </div>
          <div class="field">
            <%= f.label :commentImg, "口コミ画像", class: "reviewForm__content" %>
            <%= f.file_field :commentImg %>
          </div>
          <div class="actions">
            <%= f.submit "投稿する", method: :patch %>
          </div>
        <% end %>
      <% else %>
          <strong><p>※※※ 口コミを投稿するには新規登録/ログインが必要です ※※※</p></strong>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="contents">
  <ul>
    <li><%= link_to "利用基準", "#"%></li>
    <li><%= link_to "プライバシーポリシー", "#"%></li>
    <li><%= link_to "お問い合わせ", "#"%></li>
  </ul>

  <div class="copyright">
    <p>©︎ 2020. ALL Rights My Salad Chiken </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="uk-navbar-container uk-margin nav-center" uk-navbar>
  <ul class="uk-navbar-nav">
    <li><%= link_to image_tag("logo/logo.jpg"),"/" %></li>
    <li><%= link_to favorites_path do %><i class="fa fa-signal"></i>ランキング<% end %></li>
    <li><%= link_to item_list_items_path do %><i class="fa fa-drumstick-bite"></i>アイテムを探す<% end %></li>
    <li><%= link_to brand_index_items_path do %><i class="fa fa-industry"></i>ブランドを探す<% end %></li>
    <li><%= link_to item_reviews_path(1) do %><i class="fa fa-search"></i>口コミを探す<% end %></li>
    <% if user_signed_in? %>
      <li><%= link_to "#" do %><i class="fa fa-plus"></i>口コミを投稿する<% end %></li>
      <li>
        <%= link_to "マイページ", "#", class: "userPage" %>
        <div class="uk-navbar-dropdown">
          <ul class="uk-nav uk-navbar-dropdown-nav">
            <li><%= link_to "マイページ", user_path(current_user.id) %></li>
            <li><%= link_to destroy_user_session_path do %><i class="fa fa-sign-in-alt"></i>ログアウト<% end %></li>
          </ul>
        </div>
        
      </li>
    <% else %>
      <li><%= link_to new_user_registration_path do %><i class="fa fa-file"></i>新規登録<% end %></li>
      <li><%= link_to user_session_path do %><i class="fa fa-sign-in-alt"></i>ログイン<% end %></li>
      <li><%= link_to users_guest_sign_in_path, method: :post do %><i class="fa fa-vial"></i>ゲストログイン<% end %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/_notifications.html.erb
<div class="Notification">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: key %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MySaladChicken</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/notifications" %>
    <header>
      <%= render "layouts/header" %>
    </header>
    <%= yield %>
    <footer>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>